main: com.github.veikkosuhonen.shopmonitor.ShopMonitor
api-version: '1.16'

name: ShopMonitor
version: '0.3.3'
description: ShopMonitor allows players to monitor interactions with containers
author: Veikmaster
website: github.com/Veikkosuhonen/ShopMonitor

commands:
  monitor:
    description: ShopMonitor command
    permission: monitor.core
    usage: "Usage: /<command> [install <name> | view [-details] | list]"

  monitorop:
    description: Operator command to see monitors in containers
    permission: monitor.op
    usage: "Usage /<command> truesight"

permissions:
  monitor.core:
    description: Core functionality
    default: true

  monitor.op:
    description: Operator functionality
    default: op